# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('published_date', models.DateTimeField(blank=True)),
                ('craft', models.ImageField(upload_to='craft')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.LibGroup')),
            ],
        ),
    ]
