# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100)),
                ('image_link', models.ImageField(upload_to='gallery/')),
                ('image_description', models.TextField()),
                ('image_time_created', models.DateTimeField(auto_now_add=True)),
                ('image_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lib.Category')),
                ('image_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lib.Location')),
            ],
            options={
                'ordering': ['image_name'],
            },
        ),
    ]
