# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 13:05
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0006_auto_20180628_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_link',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
        migrations.AlterField(
            model_name='technique',
            name='craft',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
