# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 13:11
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0007_auto_20180628_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_link',
        ),
        migrations.RemoveField(
            model_name='technique',
            name='craft',
        ),
        migrations.AddField(
            model_name='image',
            name='image_upload',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
        migrations.AddField(
            model_name='technique',
            name='craft_upload',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
